
%truss
x = [cosd(theta)^2 cosd(theta)*sind(theta) -cosd(theta)^2 -cosd(theta)*sind(theta);...
    cosd(theta)*sind(theta) sind(theta)^2 -cosd(theta)*sind(theta) -sind(theta)^2;...
    -cosd(theta)^2 -cosd(theta)*sind(theta) cosd(theta)^2 cosd(theta)*sind(theta);...
    -cosd(theta)*sind(theta) -sind(theta)^2 cosd(theta)*sind(theta) sind(theta)^2];